apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ij8j8vrox-nodejs 
  janus-idp.io/tekton: ij8j8vrox-nodejs
  backstage.io/kubernetes-id: ij8j8vrox-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ij8j8vrox-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml